* About
#+begin_export markdown
[![Hatch project](https://img.shields.io/badge/%F0%9F%A5%9A-Hatch-4051b5.svg)](https://github.com/pypa/hatch)
#+end_export
A *pure-python*[fn:butwhy] project to provide unit-aware uniform visualizations
of common computational chemistry tasks. Essentially this means we provide:
- Plotting scripts for specific workflows
- Parsers for various software outputs

This is a spin-off from ~wailord~ ([[https://wailord.xyz][here]]) which is meant to handle aggregated
runs in a specific workflow, while here the goal is to do no input handling and
very pragmatic output parsing, with the goal of generating uniform plots.
** Features
- [[https://www.fabiocrameri.ch/colourmaps/][Scientific color maps]] for the plots
  + Camera ready
- Unit preserving
  + Via ~pint~

*** Supported Engines [WIP]
- ORCA (*5.x*)
  + Scanning energies over a degree of freedom (~OPT~ scans)
  + Nudged elastic band (~NEB~) visualizations (over the "linearized" reaction
    coordinate)
** Rationale
~wailord~ is for production runs, however often there is a need to collect
"spot" calculation visualizations, which should nevertheless be uniform, i.e.
either Bohr/Hartree or Angstron/eV or whatever.

Also I couldn't find (m)any scripts using the scientific colorschemes.
* License
MIT. However, this is an academic resource, so *please cite* as much as possible
via:
- The Zenodo DOI for general use.
- The ~wailord~ paper for ORCA usage

[fn:butwhy] To distinguish it from my other thin-python wrapper projects
