# SPDX-FileCopyrightText: 2023-present Rohit Goswami <rog32@hi.is>
#
# SPDX-License-Identifier: MIT
"""Minimal CON band fixtures for readcon integration tests."""

from __future__ import annotations

from pathlib import Path


def band_text(frames: list[tuple[float, float]], *, extra_meta: dict | None = None) -> str:
    """Build multi-frame CON text. Each item is ``(energy_eV, z)`` for a single H."""
    blocks = []
    for idx, (energy, z) in enumerate(frames):
        meta = {"con_spec_version": 2, "energy": energy, "frame_index": idx}
        if extra_meta:
            meta.update(extra_meta)
        meta_json = (
            '{"con_spec_version":%(con_spec_version)d,'
            '"energy":%(energy)r,"frame_index":%(frame_index)d'
            % meta
        )
        for key, value in meta.items():
            if key in {"con_spec_version", "energy", "frame_index"}:
                continue
            meta_json += f',"{key}":{value!r}'
        meta_json += "}"
        blocks.append(
            "\n".join(
                [
                    "Generated by test",
                    meta_json,
                    "10.000000 10.000000 10.000000",
                    "90.000000 90.000000 90.000000",
                    "postBox_header_1",
                    "postBox_header_2",
                    "1",
                    "1",
                    "1.008000",
                    "H",
                    "Coordinates of Component 1",
                    f"0.000000 0.000000 {z:.6f} 0 0",
                ]
            )
        )
    return "\n".join(blocks) + "\n"


def write_band(path: Path, frames: list[tuple[float, float]], **kwargs) -> Path:
    path.write_text(band_text(frames, **kwargs))
    return path


def min_metadata_band(
    path: Path, rows: list[tuple[float, float, float]]
) -> Path:
    """Write minimization movie frames.

    Each row is ``(energy, step_size, convergence)`` with sequential frame_index.
    """
    blocks = []
    for frame_index, (energy, step_size, convergence) in enumerate(rows):
        blocks.append(
            "\n".join(
                [
                    "Generated by test",
                    (
                        '{"con_spec_version":2,'
                        f'"frame_index":{frame_index},'
                        f'"energy":{energy!r},'
                        f'"step_size":{step_size!r},'
                        f'"convergence":{convergence!r}'
                        "}"
                    ),
                    "10.000000 10.000000 10.000000",
                    "90.000000 90.000000 90.000000",
                    "postBox_header_1",
                    "postBox_header_2",
                    "1",
                    "1",
                    "1.008000",
                    "H",
                    "Coordinates of Component 1",
                    f"0.000000 0.000000 {0.1 * frame_index:.6f} 0 0",
                ]
            )
        )
    path.write_text("\n".join(blocks) + "\n")
    return path
