# SPDX-FileCopyrightText: 2023-present Rohit Goswami <rog32@hi.is>
#
# SPDX-License-Identifier: MIT
"""Tests for stitching multiple NEB segments into one continuous band."""

from __future__ import annotations

import pytest

readcon = pytest.importorskip("readcon")

import itertools

from chemparseplot.parse.eon.stitch import stitch_neb_segments


def _write_band(path, frames):
    """Write a minimal single-atom .con band; ``frames`` is a list of (energy, z)."""
    blocks = []
    for energy, z in frames:
        blocks.append(
            "\n".join(
                [
                    "Generated by test",
                    f'{{"con_spec_version":2,"energy":{energy!r}}}',
                    "10.000000 10.000000 10.000000",
                    "90.000000 90.000000 90.000000",
                    "postBox_header_1",
                    "postBox_header_2",
                    "1",
                    "1",
                    "1.008000",
                    "H",
                    "Coordinates of Component 1",
                    f"0.000000 0.000000 {z:.6f} 0 0",
                ]
            )
        )
    path.write_text("\n".join(blocks) + "\n")


def test_stitch_two_segments_dedupes_and_aligns(tmp_path):
    # Segment A: energies 0 -> 1 at z = 0.0, 0.5
    # Segment B: starts at z = 0.5 (duplicate of A's last frame) with a constant
    # +10 eV minimization offset, then climbs by 1 eV.
    band_a = tmp_path / "a.con"
    band_b = tmp_path / "b.con"
    _write_band(band_a, [(0.0, 0.0), (1.0, 0.5)])
    _write_band(band_b, [(10.0, 0.5), (11.0, 1.0)])

    out_dir = tmp_path / "stitched"
    summary = stitch_neb_segments(
        [("A", band_a, 0, 2), ("B", band_b, 0, 2)],
        out_dir,
    )

    # Junction dedup: 4 input frames - 1 duplicate = 3 frames.
    assert summary.n_frames == 3
    assert summary.boundary_indices == [0, 2]

    frames = readcon.read_con(str(out_dir / "neb.con"))
    assert len(frames) == 3

    energies = [f.energy for f in frames]
    # Referenced to the first frame (reactant = 0) and continuous across the
    # junction: B's +10 eV offset is removed, so the kept B frame extends A's
    # last frame by B's internal 1 eV step (1.0 -> 2.0), not a 10 eV jump.
    assert energies == pytest.approx([0.0, 1.0, 2.0])

    # Energy continuity at the junction equals B's own internal step.
    junction_step = energies[2] - energies[1]
    assert junction_step == pytest.approx(1.0)


def test_cumulative_rmsd_matches_stepwise_and_is_vectorized():
    """Shipped cumulative RMSD agrees with per-frame steps (vectorized path)."""
    import numpy as np

    from chemparseplot.parse.eon.stitch import _cartesian_rmsd, _cumulative_rmsd

    class _A:
        def __init__(self, p):
            self._p = np.asarray(p, dtype=float)

        def get_positions(self):
            return self._p

    rng = np.random.default_rng(42)
    atoms = [_A(rng.normal(size=(12, 3))) for _ in range(25)]
    got = _cumulative_rmsd(atoms)
    slow = [0.0]
    for prev, cur in itertools.pairwise(atoms):
        slow.append(slow[-1] + _cartesian_rmsd(prev, cur))
    assert np.allclose(got, slow)
    assert got[0] == 0.0
    assert len(got) == len(atoms)


def test_stitch_writes_sidecar_artifacts_via_con_io(tmp_path):
    from chemparseplot.parse.eon.con_io import read_con_frames

    band_a = tmp_path / "a.con"
    band_b = tmp_path / "b.con"
    _write_band(band_a, [(0.0, 0.0), (1.0, 0.5), (0.5, 1.0)])
    _write_band(band_b, [(10.5, 1.0), (11.5, 1.5)])
    out_dir = tmp_path / "stitched"
    summary = stitch_neb_segments(
        [("A", band_a, None, None), ("B", band_b, None, None)],
        out_dir,
    )

    neb = read_con_frames(out_dir / "neb.con")
    path0 = read_con_frames(out_dir / "neb_path_000.con")
    sp = read_con_frames(out_dir / "sp.con")
    assert len(neb) == summary.n_frames == 4
    assert [f.energy for f in neb] == pytest.approx([f.energy for f in path0])
    assert len(sp) == 1
    assert sp[0].energy == pytest.approx(summary.highest_energy)
    dat = (out_dir / "neb_000.dat").read_text().strip().splitlines()
    assert dat[0].split()[:3] == ["img", "rxn_coord", "energy"]
    assert len(dat) == summary.n_frames + 1
    assert summary.segments[0].label == "A"
    assert summary.segments[1].barrier == pytest.approx(
        summary.segments[1].peak_energy - summary.segments[1].well_energy
    )


def test_stitch_saddle_override_writes_sp_energy(tmp_path):
    from ase import Atoms

    from chemparseplot.parse.eon.con_io import read_con_frames, write_atoms_as_con

    band_a = tmp_path / "a.con"
    band_b = tmp_path / "b.con"
    _write_band(band_a, [(0.0, 0.0), (1.0, 0.5)])
    _write_band(band_b, [(10.0, 0.5), (12.0, 1.0)])
    sad = tmp_path / "dimer_saddle.con"
    write_atoms_as_con(
        sad,
        [Atoms("H", positions=[[0.0, 0.0, 0.75]], cell=[10, 10, 10], pbc=True)],
        energies=[11.5],
    )
    out_dir = tmp_path / "stitched"
    summary = stitch_neb_segments(
        [("A", band_a, 0, None), ("B", band_b, 0, None)],
        out_dir,
        saddle_overrides={"B": (sad, 11.5)},
    )
    sp = read_con_frames(out_dir / "sp.con")
    assert len(sp) == 1
    # A ends at 1.0 eV; B shift is 1.0 - 10.0 = -9.0, so referenced saddle is
    # 11.5 - 9.0 - 0.0 = 2.5 eV on the global reactant scale.
    assert sp[0].energy == pytest.approx(2.5)
    assert summary.segments[1].peak_energy == pytest.approx(2.5)
    # well_energy is the segment entry (junction) on the global scale (= 1.0 eV).
    assert summary.segments[1].well_energy == pytest.approx(1.0)
    assert summary.segments[1].barrier == pytest.approx(1.5)
    # highest_energy tracks the stitched band maximum (kept B frame at 3.0 eV),
    # while sp.con carries the override geometry/energy for overlay plotting.
    assert summary.highest_energy == pytest.approx(3.0)
    band_energies = [frame.energy for frame in read_con_frames(out_dir / "neb.con")]
    assert max(band_energies) == pytest.approx(3.0)


def test_stitch_empty_slice_raises(tmp_path):
    band = tmp_path / "a.con"
    _write_band(band, [(0.0, 0.0), (1.0, 0.5)])
    with pytest.raises(ValueError, match="zero frames"):
        stitch_neb_segments([("A", band, 2, 2)], tmp_path / "out")
