# SPDX-FileCopyrightText: 2023-present Rohit Goswami <rog32@hi.is>
#
# SPDX-License-Identifier: MIT
"""Tests for stitching multiple NEB segments into one continuous band."""

from __future__ import annotations

import pytest

readcon = pytest.importorskip("readcon")

from chemparseplot.parse.eon.stitch import stitch_neb_segments


def _write_band(path, frames):
    """Write a minimal single-atom .con band; ``frames`` is a list of (energy, z)."""
    blocks = []
    for energy, z in frames:
        blocks.append(
            "\n".join(
                [
                    "Generated by test",
                    '{"con_spec_version":2,"energy":%r}' % energy,
                    "10.000000 10.000000 10.000000",
                    "90.000000 90.000000 90.000000",
                    "postBox_header_1",
                    "postBox_header_2",
                    "1",
                    "1",
                    "1.008000",
                    "H",
                    "Coordinates of Component 1",
                    f"0.000000 0.000000 {z:.6f} 0 0",
                ]
            )
        )
    path.write_text("\n".join(blocks) + "\n")


def test_stitch_two_segments_dedupes_and_aligns(tmp_path):
    # Segment A: energies 0 -> 1 at z = 0.0, 0.5
    # Segment B: starts at z = 0.5 (duplicate of A's last frame) with a constant
    # +10 eV minimization offset, then climbs by 1 eV.
    band_a = tmp_path / "a.con"
    band_b = tmp_path / "b.con"
    _write_band(band_a, [(0.0, 0.0), (1.0, 0.5)])
    _write_band(band_b, [(10.0, 0.5), (11.0, 1.0)])

    out_dir = tmp_path / "stitched"
    summary = stitch_neb_segments(
        [("A", band_a, 0, 2), ("B", band_b, 0, 2)],
        out_dir,
    )

    # Junction dedup: 4 input frames - 1 duplicate = 3 frames.
    assert summary.n_frames == 3
    assert summary.boundary_indices == [0, 2]

    frames = readcon.read_con(str(out_dir / "neb.con"))
    assert len(frames) == 3

    energies = [f.energy for f in frames]
    # Referenced to the first frame (reactant = 0) and continuous across the
    # junction: B's +10 eV offset is removed, so the kept B frame extends A's
    # last frame by B's internal 1 eV step (1.0 -> 2.0), not a 10 eV jump.
    assert energies == pytest.approx([0.0, 1.0, 2.0])

    # Energy continuity at the junction equals B's own internal step.
    junction_step = energies[2] - energies[1]
    assert junction_step == pytest.approx(1.0)
