# SPDX-FileCopyrightText: 2023-present Rohit Goswami <rog32@hi.is>
#
# SPDX-License-Identifier: MIT
"""Real-path tests for chemparseplot.parse.eon.con_io (readcon boundary)."""

from __future__ import annotations

from pathlib import Path

import pytest

readcon = pytest.importorskip("readcon")
ase = pytest.importorskip("ase")

from ase import Atoms

from chemparseplot.parse.eon import con_io
from chemparseplot.parse.eon.con_io import (
    frame_with_energy,
    is_con_path,
    read_con_as_ase,
    read_con_frames,
    read_first_atoms,
    write_atoms_as_con,
    write_con_frames,
)


def _band_text(frames: list[tuple[float, float]]) -> str:
    blocks = []
    for energy, z in frames:
        blocks.append(
            "\n".join(
                [
                    "Generated by test",
                    '{"con_spec_version":2,"energy":%r}' % energy,
                    "10.000000 10.000000 10.000000",
                    "90.000000 90.000000 90.000000",
                    "postBox_header_1",
                    "postBox_header_2",
                    "1",
                    "1",
                    "1.008000",
                    "H",
                    "Coordinates of Component 1",
                    f"0.000000 0.000000 {z:.6f} 0 0",
                ]
            )
        )
    return "\n".join(blocks) + "\n"


def test_is_con_path_suffixes():
    assert is_con_path("neb.con")
    assert is_con_path(Path("x.CONVEL"))
    assert not is_con_path("neb.traj")


def test_frame_with_energy_roundtrip(tmp_path: Path):
    src = tmp_path / "in.con"
    src.write_text(_band_text([(1.25, 0.0)]))
    frame = read_con_frames(src)[0]
    assert frame.energy == pytest.approx(1.25)

    updated = frame_with_energy(frame, -3.5)
    assert updated.energy == pytest.approx(-3.5)
    assert frame.energy == pytest.approx(1.25)

    out = tmp_path / "out.con"
    write_con_frames(out, [updated])
    back = readcon.read_con(str(out))[0]
    assert back.energy == pytest.approx(-3.5)
    assert back.to_ase().get_positions()[0, 2] == pytest.approx(0.0)


def test_write_atoms_as_con_preserves_energy(tmp_path: Path):
    atoms = Atoms("H", positions=[[0.0, 0.0, 1.5]], cell=[10, 10, 10], pbc=True)
    out = tmp_path / "atoms.con"
    write_atoms_as_con(out, [atoms], energies=[4.2])
    frames = read_con_frames(out)
    assert len(frames) == 1
    assert frames[0].energy == pytest.approx(4.2)
    ase_frames = read_con_as_ase(out)
    assert len(ase_frames) == 1
    assert ase_frames[0].get_positions()[0, 2] == pytest.approx(1.5)
    assert read_first_atoms(out).get_chemical_symbols() == ["H"]


def test_con_io_exported_from_parse_eon():
    assert con_io.read_con_frames is read_con_frames
