# SPDX-FileCopyrightText: 2023-present Rohit Goswami <rog32@hi.is>
#
# SPDX-License-Identifier: MIT
"""readcon-backed CON/convel I/O helpers (general).

Canonical home for suite CON I/O. Prefer
:mod:`chemparseplot.parse.con` over importing ``readcon`` directly.
``readcon`` remains an optional extra (``chemparseplot[neb]``).

```{versionadded} 1.8.1
```
```{versionchanged} 1.9.12
Moved from ``parse.eon.con_io`` to general ``parse.con.io``.
```
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path
from typing import Any

__all__ = [
    "CON_SUFFIXES",
    "frame_with_energy",
    "is_con_path",
    "read_con_as_ase",
    "read_con_frames",
    "read_first_atoms",
    "write_atoms_as_con",
    "write_con_frames",
]

CON_SUFFIXES = (".con", ".convel")


def is_con_path(path: str | Path) -> bool:
    """Return True when *path* looks like an eOn CON/convel file."""
    return Path(path).suffix.lower() in CON_SUFFIXES


def _readcon():
    try:
        import readcon
    except ImportError as exc:  # pragma: no cover - exercised when extra missing
        msg = (
            "readcon is required for CON I/O. Install with: "
            "pip install 'chemparseplot[neb]' (readcon>=0.7.0)"
        )
        raise ImportError(msg) from exc
    return readcon


def read_con_frames(path: str | Path) -> list[Any]:
    """Read all frames from a CON/convel file as ``readcon.ConFrame`` objects."""
    readcon = _readcon()
    return list(readcon.read_con(str(path)))


def read_con_as_ase(path: str | Path) -> list:
    """Read all frames from a CON/convel file as ASE ``Atoms`` objects."""
    readcon = _readcon()
    return list(readcon.read_con_as_ase(str(path)))


def read_first_atoms(path: str | Path):
    """Read the first frame of a CON file as an ASE ``Atoms`` object."""
    return read_con_as_ase(path)[0]


def frame_with_energy(frame: Any, energy: float) -> Any:
    """Return a ``ConFrame`` copy with per-frame total ``energy`` set (eV).

    Uses ``ConFrame.set_energy`` when available (readcon>=0.7) so metadata stays
    schema-valid; falls back to reconstructing the frame with string metadata.
    """
    readcon = _readcon()
    ConFrame = readcon.ConFrame
    metadata = frame.metadata
    if hasattr(metadata, "items"):
        metadata_dict = {str(k): v for k, v in metadata.items()}
    else:
        metadata_dict = dict(metadata or {})
    clone = ConFrame(
        frame.cell,
        frame.angles,
        frame.atoms,
        frame.prebox_header,
        frame.postbox_header,
        metadata_dict,
    )
    value = float(energy)
    setter = getattr(clone, "set_energy", None)
    if callable(setter):
        setter(value)
        return clone
    scalar = getattr(clone, "set_scalar_metadata", None)
    if callable(scalar):
        scalar("energy", value)
        return clone
    metadata_dict["energy"] = str(value)
    return ConFrame(
        frame.cell,
        frame.angles,
        frame.atoms,
        frame.prebox_header,
        frame.postbox_header,
        metadata_dict,
    )


def _normalize_box_headers(frame: Any) -> Any:
    """Ensure pre/post box headers are non-empty for multi-frame CON I/O.

    ``ConFrame.from_ase`` often yields empty header lines (``['', '']``). That
    is fine for a single frame, but multi-frame ``write_con`` then fails to
    re-parse (velocity-section EOF). Match the conventional ASE/eOn layout with
    two non-empty header lines each.
    """
    pre = list(getattr(frame, "prebox_header", None) or [])
    post = list(getattr(frame, "postbox_header", None) or [])
    pre_ok = bool(pre) and any(str(x).strip() for x in pre)
    post_ok = bool(post) and any(str(x).strip() for x in post)
    if pre_ok and post_ok:
        return frame
    if not pre_ok:
        pre = ["Generated by chemparseplot", "preBox_header_2"]
    if not post_ok:
        post = ["postBox_header_1", "postBox_header_2"]
    readcon = _readcon()
    ConFrame = readcon.ConFrame
    metadata = frame.metadata
    if hasattr(metadata, "items"):
        metadata_dict = {str(k): v for k, v in metadata.items()}
    else:
        metadata_dict = dict(metadata or {})
    return ConFrame(
        frame.cell,
        frame.angles,
        frame.atoms,
        pre,
        post,
        metadata_dict,
    )


def write_con_frames(path: str | Path, frames: Sequence[Any]) -> Path:
    """Write ``ConFrame`` objects to *path* via ``readcon.write_con``.

    Multi-frame movies normalize empty ASE box headers so the written file
    re-parses with readcon-core (see :func:`_normalize_box_headers`).
    """
    readcon = _readcon()
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    normalized = [_normalize_box_headers(fr) for fr in frames]
    # Preserve energy / frame_index that may live only on the original object
    for src, dst in zip(frames, normalized):
        if src is dst:
            continue
        e = getattr(src, "energy", None)
        if e is not None and callable(getattr(dst, "set_energy", None)):
            dst.set_energy(float(e))
        fi = getattr(src, "frame_index", None)
        if fi is not None and callable(getattr(dst, "set_frame_index", None)):
            dst.set_frame_index(int(fi))
    readcon.write_con(str(out), list(normalized))
    return out


def write_atoms_as_con(
    path: str | Path,
    atoms_list: Sequence[Any],
    *,
    energies: Sequence[float | None] | None = None,
) -> Path:
    """Convert ASE ``Atoms`` to ``ConFrame`` and write a CON file.

    Optional *energies* (eV) are attached per frame with :func:`frame_with_energy`.
    Multi-frame output is round-trip safe with readcon-core ≥0.13.
    """
    readcon = _readcon()
    frames = []
    for idx, atoms in enumerate(atoms_list):
        frame = readcon.ConFrame.from_ase(atoms)
        if energies is not None and idx < len(energies) and energies[idx] is not None:
            frame = frame_with_energy(frame, float(energies[idx]))
        if callable(getattr(frame, "set_frame_index", None)):
            frame.set_frame_index(idx)
        frames.append(frame)
    return write_con_frames(path, frames)
