#+TITLE: Used By
#+AUTHOR: [[https://rgoswami.me][Rohit Goswami]]
#+OPTIONS: toc:nil todo:nil num:nil author:t title:t ^:nil

The following projects use ~chemparseplot~ as a dependency or tool.

* Libraries

- [[https://rgpycrumbs.rgoswami.me][rgpycrumbs]] :: Core types, surfaces, and
  CLI dispatcher. ~chemparseplot~ imports ~rgpycrumbs~ for GP landscapes and
  interpolation; rgpycrumbs CLI dispatches back here for plotting.
- [[https://pychum.rgoswami.me][pychum]] :: Input file generators for
  computational chemistry. Companion: ~pychum~ writes inputs,
  ~chemparseplot~ reads outputs.

* Reproducibility Packages

- [[https://github.com/HaoZeke/brms_idrot_repro][brms_idrot_repro]] :: Bayesian
  reaction mechanism studies reproduction package. Uses both ~chemparseplot~
  and ~rgpycrumbs~ for parsing and analysis.

* Academic Work

- Rohit Goswami, /Efficient Exploration of Chemical Kinetics/, Doctoral
  dissertation, University of Iceland, 2025.
  arXiv: [[https://arxiv.org/abs/2510.21368][2510.21368]],
  doi: [[https://doi.org/10.48550/arXiv.2510.21368][10.48550/arXiv.2510.21368]].
  Uses ~chemparseplot~ for parsing and plotting computational chemistry outputs.
