# SPDX-FileCopyrightText: 2023-present Rohit Goswami <rog32@hi.is>
#
# SPDX-License-Identifier: MIT
"""XYZ grammar track tests."""

from __future__ import annotations

from pathlib import Path

import pytest

pytest.importorskip("parsimonious")

from chemparseplot.parse.grammar.xyz import (  # noqa: E402
    parse_xyz_file,
    parse_xyz_text,
    write_xyz_text,
)

FIXTURES = Path(__file__).resolve().parents[2] / "fixtures"


def test_parse_h2mol_fixture():
    frame = parse_xyz_file(FIXTURES / "h2mol.xyz")
    assert frame.natoms == 2
    assert frame.comment.startswith("XYZ file generated by Avogadro")
    assert frame.symbols == ["H", "H"]
    assert frame.counts == {"H": 2}
    assert frame.system == "H2"
    assert len(frame.coordinates()) == 2


def test_parse_multichar_elements():
    text = """3
comment
He   0.0  0.0  0.0
Cl   1.0  0.0  0.0
H    0.0  1.0  0.0
"""
    frame = parse_xyz_text(text)
    assert frame.natoms == 3
    assert frame.symbols == ["He", "Cl", "H"]


def test_write_roundtrip_natoms_and_symbols():
    frame = parse_xyz_file(FIXTURES / "h2mol.xyz")
    out = write_xyz_text(frame, comment="roundtrip")
    back = parse_xyz_text(out)
    assert back.natoms == 2
    assert back.symbols == ["H", "H"]
    assert back.comment == "roundtrip"


def test_natoms_mismatch_raises():
    text = """1
bad
H 0 0 0
H 1 1 1
"""
    with pytest.raises(ValueError, match="natoms"):
        parse_xyz_text(text)
