name: lints
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
on:
  push:
    branches: [main]
  pull_request:
jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Run precommit
      run: |
        uvx prek run -a -vvv
    - name: Link check (advisory)
      continue-on-error: true
      run: |
        cargo install lychee@0.23.0 --locked
        lychee --no-progress --cache --max-cache-age=1d --accept '200..=399' $(git ls-files '*.md' '*.rst' '*.html')
